'use server';

/**
 * Server actions for the site editor.
 *
 * Security model:
 *   - Every action calls `requireCustomerSiteAccess(siteId)` first (fail-closed).
 *   - `siteId` comes from a hidden form field and is checked BEFORE any Sanity
 *     read, closing the IDOR vector.
 *   - Only paths generated by the fields registry are ever written to Sanity.
 *     The patch set is built server-side from `buildPatchSet` — no client path
 *     is trusted.
 *   - Hard-blocked fields (draftMode, robotsDisallow, slug, etc.) are never
 *     in the allowlist and are explicitly locked in `publishSite` before the
 *     promote action.
 */

import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import {
  requireCustomerSiteAccess,
  UnauthorizedError,
} from '@/lib/auth-guard';
import {
  getEditableDoc,
  saveFields,
  publishSite,
  discardDraft,
  uploadAndSetImage,
  getAiImageGenerationCount,
  incrementAiImageGenerationCount,
  AI_IMAGE_GENERATION_LIMIT,
} from '@/lib/sanity-write';
import { validateFormValues, buildPatchSet } from '@/lib/fields';
import { generateHeroImageBuffer } from '@leadlandlord/integrations/imagen';

// ---------------------------------------------------------------------------
// Save action
// ---------------------------------------------------------------------------

export interface SaveResult {
  ok: boolean;
  errors?: Record<string, string>;
  message?: string;
  /** True when the save succeeded but there was nothing to write. */
  noop?: boolean;
}

/**
 * Validates submitted form values and patches the Sanity draft.
 *
 * FormData must include a `siteId` hidden field. All other entries are treated
 * as potential field values and validated against the zod allowlist.
 */
export async function saveAction(_prev: SaveResult, formData: FormData): Promise<SaveResult> {
  const siteId = String(formData.get('siteId') ?? '').trim();
  if (!siteId) return { ok: false, message: 'Missing site ID.' };

  // Auth guard first — before any Sanity read.
  try {
    await requireCustomerSiteAccess(siteId);
  } catch (err) {
    if (err instanceof UnauthorizedError) {
      redirect('/login');
    }
    return { ok: false, message: 'Access denied.' };
  }

  // Collect form values (everything except siteId).
  const raw: Record<string, string> = {};
  for (const [key, value] of formData.entries()) {
    if (key === 'siteId') continue;
    if (typeof value === 'string') {
      raw[key] = value;
    }
  }

  // Validate against the allowlist zod schemas.
  const validation = validateFormValues(raw);
  if (!validation.ok) {
    return { ok: false, errors: validation.errors };
  }

  // Read current doc to resolve sub-array _key values.
  const doc = await getEditableDoc(siteId);
  if (!doc) {
    return { ok: false, message: 'Site content not found. It may still be building.' };
  }

  // Build granular Sanity patch paths.
  const patchSet = buildPatchSet(doc, validation.values);

  if (Object.keys(patchSet).length === 0) {
    return { ok: true, noop: true }; // Nothing changed.
  }

  try {
    await saveFields(siteId, patchSet);
  } catch (err) {
    return {
      ok: false,
      message: err instanceof Error ? err.message : 'Save failed. Please try again.',
    };
  }

  revalidatePath(`/sites/${siteId}/edit`);
  return { ok: true };
}

// ---------------------------------------------------------------------------
// Publish action
// ---------------------------------------------------------------------------

export interface PublishResult {
  ok: boolean;
  message?: string;
}

/**
 * Promotes the draft to published. Sets safety locks (draftMode:false,
 * robotsDisallow:false) before the atomic promote action.
 */
export async function publishAction(siteId: string): Promise<PublishResult> {
  if (!siteId) return { ok: false, message: 'Missing site ID.' };

  try {
    await requireCustomerSiteAccess(siteId);
  } catch (err) {
    if (err instanceof UnauthorizedError) {
      redirect('/login');
    }
    return { ok: false, message: 'Access denied.' };
  }

  try {
    await publishSite(siteId);
    revalidatePath(`/sites/${siteId}/edit`);
    return { ok: true };
  } catch (err) {
    return {
      ok: false,
      message: err instanceof Error ? err.message : 'Publish failed. Please try again.',
    };
  }
}

// ---------------------------------------------------------------------------
// Discard action
// ---------------------------------------------------------------------------

export interface DiscardResult {
  ok: boolean;
  message?: string;
}

/**
 * Discards the draft, reverting to the last published version.
 */
export async function discardAction(siteId: string): Promise<DiscardResult> {
  if (!siteId) return { ok: false, message: 'Missing site ID.' };

  try {
    await requireCustomerSiteAccess(siteId);
  } catch (err) {
    if (err instanceof UnauthorizedError) {
      redirect('/login');
    }
    return { ok: false, message: 'Access denied.' };
  }

  try {
    await discardDraft(siteId);
    revalidatePath(`/sites/${siteId}/edit`);
    return { ok: true };
  } catch (err) {
    return {
      ok: false,
      message: err instanceof Error ? err.message : 'Discard failed. Please try again.',
    };
  }
}

// ---------------------------------------------------------------------------
// Image upload action
// ---------------------------------------------------------------------------

/**
 * Allowed image field keys. Must stay in sync with IMAGE_FIELD_PATHS in
 * lib/sanity-write.ts. Checked here (server action boundary) before
 * uploadAndSetImage also validates.
 */
const ALLOWED_IMAGE_FIELD_KEYS = new Set([
  'logo',
  'favicon',
  'hero.image',
  'about.image',
  'seo.ogImage',
]);

export interface UploadImageResult {
  ok: boolean;
  assetUrl?: string;
  error?: string;
}

/**
 * Uploads an image file for one of the four permitted image fields and
 * patches the Sanity draft.
 *
 * FormData must contain:
 *   - `file`     — the File object
 *   - `fieldKey` — one of 'logo' | 'favicon' | 'hero.image' | 'about.image'
 *
 * Security:
 *   - `requireCustomerSiteAccess(siteId)` is called first (fail-closed).
 *   - fieldKey is validated against the hard-coded allowlist.
 *   - contentType and byte-length are validated server-side (not trusted from client).
 */
export async function uploadImageAction(
  siteId: string,
  fieldKey: string,
  formData: FormData,
): Promise<UploadImageResult> {
  if (!siteId) return { ok: false, error: 'Missing site ID.' };

  // 1. Auth guard first.
  try {
    await requireCustomerSiteAccess(siteId);
  } catch (err) {
    if (err instanceof UnauthorizedError) {
      redirect('/login');
    }
    return { ok: false, error: 'Access denied.' };
  }

  // 2. Allowlist check on fieldKey.
  if (!ALLOWED_IMAGE_FIELD_KEYS.has(fieldKey)) {
    return { ok: false, error: `Image field '${fieldKey}' is not permitted.` };
  }

  // 3. Read the File from FormData.
  const file = formData.get('file');
  if (!(file instanceof File)) {
    return { ok: false, error: 'No file provided.' };
  }

  if (file.size === 0) {
    return { ok: false, error: 'File is empty.' };
  }

  // 4. Validate content type from the File object (declared by the browser,
  //    but we also rely on uploadAndSetImage to enforce it).
  const contentType = file.type;

  // 5. Convert to Buffer for the Sanity upload API.
  const arrayBuffer = await file.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);

  // 6. Delegate to the write helper (validates type + size + allowlist again).
  try {
    const result = await uploadAndSetImage(siteId, fieldKey, {
      buffer,
      filename: file.name,
      contentType,
    });
    return { ok: true, assetUrl: result.assetUrl };
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : 'Upload failed. Please try again.',
    };
  }
}

// ---------------------------------------------------------------------------
// AI image generation (Google Imagen)
// ---------------------------------------------------------------------------

/** Target field -> Imagen aspect ratio. Also serves as the allowlist. */
const GENERATE_ASPECT: Record<string, '16:9' | '4:3' | '1:1' | '3:2'> = {
  'logo': '1:1',
  'hero.image': '16:9',
  'about.image': '4:3',
  'seo.ogImage': '16:9',
};

export interface GenerateImageResult {
  ok: boolean;
  assetUrl?: string;
  /** Generations remaining for this site after this call. */
  remaining?: number;
  error?: string;
}

/**
 * Generates an image from a customer prompt via Google Imagen, uploads it to
 * Sanity, and sets it on the chosen image field of the draft.
 *
 * Security / limits:
 *   - `requireCustomerSiteAccess(siteId)` first (fail-closed).
 *   - `fieldKey` validated against GENERATE_ASPECT (same four image targets).
 *   - Hard cap of AI_IMAGE_GENERATION_LIMIT per site, enforced server-side on a
 *     counter stored on the PUBLISHED doc. Only successful generations count.
 */
export async function generateImageAction(
  siteId: string,
  fieldKey: string,
  prompt: string,
): Promise<GenerateImageResult> {
  if (!siteId) return { ok: false, error: 'Missing site ID.' };

  // 1. Auth guard first.
  try {
    await requireCustomerSiteAccess(siteId);
  } catch (err) {
    if (err instanceof UnauthorizedError) {
      redirect('/login');
    }
    return { ok: false, error: 'Access denied.' };
  }

  // 2. Target allowlist.
  const aspectRatio = GENERATE_ASPECT[fieldKey];
  if (!aspectRatio) {
    return { ok: false, error: `Image field '${fieldKey}' is not permitted.` };
  }

  // 3. Prompt validation.
  const clean = (prompt ?? '').trim();
  if (clean.length < 3) return { ok: false, error: 'Please describe the image you want (a few words).' };
  if (clean.length > 500) return { ok: false, error: 'Description is too long (max 500 characters).' };
  if (clean.includes('<')) return { ok: false, error: 'Description contains invalid characters.' };

  // 4. Usage limit — check BEFORE spending on generation.
  const used = await getAiImageGenerationCount(siteId);
  if (used >= AI_IMAGE_GENERATION_LIMIT) {
    return {
      ok: false,
      remaining: 0,
      error: `You've used all ${AI_IMAGE_GENERATION_LIMIT} AI image generations for this site.`,
    };
  }

  // 5. Generate the image.
  let img;
  try {
    img = await generateHeroImageBuffer(clean, {
      aspectRatio,
      negativePrompt: 'text, words, letters, watermark, signature, blurry, low quality, distorted',
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Image generation failed. Please try again.' };
  }
  if (!img) {
    return {
      ok: false,
      error: 'Image generation is currently unavailable. Please upload your own image instead.',
    };
  }

  // 6. Upload + set on the chosen field (reuses type/size/magic-byte validation
  //    and the draft patch), then count the successful generation.
  try {
    const ext = img.contentType === 'image/png' ? 'png' : 'jpg';
    const result = await uploadAndSetImage(siteId, fieldKey, {
      buffer: img.buffer,
      filename: `ai-${fieldKey.replace(/[^a-z0-9]+/gi, '-')}.${ext}`,
      contentType: img.contentType,
    });
    const newUsed = await incrementAiImageGenerationCount(siteId);
    revalidatePath(`/sites/${siteId}/edit`);
    return {
      ok: true,
      assetUrl: result.assetUrl,
      remaining: Math.max(0, AI_IMAGE_GENERATION_LIMIT - newUsed),
    };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Could not save the generated image.' };
  }
}
