-- R4.2 Molly backlinks pipeline: new enum, new table, enum extensions, new columns
-- DO NOT edit this file after it has been applied to any environment.

-- ── 1. New enum for backlink_prospects ──────────────────────────────────────
CREATE TYPE backlink_prospect_status AS ENUM (
  'prospected',
  'scored',
  'flagged_top5',
  'approved',
  'pitched'
);
--> statement-breakpoint

-- ── 2. New table: backlink_prospects ────────────────────────────────────────
--
-- Tracks candidate domains from DFS discovery through operator approval.
-- Separate from the existing `prospects` table which is the tenant sales CRM.
--
CREATE TABLE backlink_prospects (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id         uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  domain          text NOT NULL,
  domain_rank     integer,
  status          backlink_prospect_status NOT NULL DEFAULT 'prospected',
  score           numeric(5, 2),
  rationale       text,
  flagged_top5_at timestamptz,
  approved_at     timestamptz,
  backlink_id     uuid REFERENCES backlinks(id) ON DELETE SET NULL,
  -- dedupe_key: 'prospect:<siteId>:<domain>' — prevents re-discovering the same
  -- domain for the same site in back-to-back DFS runs.
  dedupe_key      text UNIQUE NULLS NOT DISTINCT,
  metadata        jsonb,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW()
);
--> statement-breakpoint

CREATE INDEX backlink_prospects_site_status_idx
  ON backlink_prospects (site_id, status);
--> statement-breakpoint

CREATE INDEX backlink_prospects_flagged_top5_at_idx
  ON backlink_prospects (flagged_top5_at DESC)
  WHERE flagged_top5_at IS NOT NULL;
--> statement-breakpoint

-- ── 3. Extend backlink_status enum ──────────────────────────────────────────
--
-- These are additive-only (ALTER TYPE … ADD VALUE). Postgres does not require
-- a table rewrite for enum extensions. Values are added in the order they
-- appear in the state machine (ADR-0006).
--
-- Convention (document here to prevent future confusion):
--   `live`      — used by citation/directory rows to mean "the link is live."
--   `published` — used by guest-post rows after the post is confirmed live.
--   `verified`  — used by guest-post rows after GSC confirms the link is indexed.
-- Do NOT use `live` for guest-post rows; use `published` → `verified`.
--
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'awaiting_reply'      AFTER 'submitted';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'reply_received'      AFTER 'awaiting_reply';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'accepted'            AFTER 'reply_received';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'declined'            AFTER 'accepted';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'silent'              AFTER 'declined';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'escalated'           AFTER 'silent';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'drafting'            AFTER 'escalated';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'draft_pending_review' AFTER 'drafting';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'draft_approved'      AFTER 'draft_pending_review';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'delivered'           AFTER 'draft_approved';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'published'           AFTER 'delivered';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'verified'            AFTER 'published';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'dormant'             AFTER 'verified';
--> statement-breakpoint
ALTER TYPE backlink_status ADD VALUE IF NOT EXISTS 'manual_review'       AFTER 'dormant';
--> statement-breakpoint

-- ── 4. New columns on backlinks ─────────────────────────────────────────────
ALTER TABLE backlinks
  ADD COLUMN IF NOT EXISTS message_id     text,
  ADD COLUMN IF NOT EXISTS anchor_type    text
    CONSTRAINT backlinks_anchor_type_chk
      CHECK (anchor_type IN ('branded', 'naked', 'generic', 'partial')),
  ADD COLUMN IF NOT EXISTS draft_markdown text,
  ADD COLUMN IF NOT EXISTS published_at   timestamptz,
  ADD COLUMN IF NOT EXISTS published_url  text,
  ADD COLUMN IF NOT EXISTS nudge_count    integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_nudge_at  timestamptz;
--> statement-breakpoint

-- ── 5. Index: backlinks.message_id ──────────────────────────────────────────
--
-- MollyInbox filters inbound Zoho threads by matching In-Reply-To against this
-- column. Partial index — message_id is null on all non-guest-post rows.
--
CREATE INDEX backlinks_message_id_idx
  ON backlinks (message_id)
  WHERE message_id IS NOT NULL;
