-- R4.3 BCC graduation: per-agent counter for the first-N-sends BCC policy.
-- DO NOT edit this file after it has been applied to any environment.

CREATE TABLE bcc_graduation (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name      text NOT NULL UNIQUE,
  outbound_count  integer NOT NULL DEFAULT 0,
  graduated_at    timestamptz,
  manual_override boolean NOT NULL DEFAULT false,
  bcc_address     text,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW()
);
--> statement-breakpoint

INSERT INTO bcc_graduation (agent_name) VALUES ('molly')
ON CONFLICT (agent_name) DO NOTHING;
