// Seed taxonomy of local service-business trades, grouped by the 9 niche-hunter
// categories. Injected into the brainstorm system prompt to broaden scope beyond
// the saturated home-services tropes the model defaults to. The category keys
// here MUST stay in sync with the CategoryEnum defined in index.ts
// (home_services, auto, health, professional, pet, event, lifestyle, legal, medical).
//
// legal/medical are licensed professions. The platform does NOT verify licenses —
// every site is rented to a real contractor/practice who brings their own license,
// GBP, and regulated-profession ad compliance (bar/board disclaimers, no outcome
// guarantees). Scope here is deliberately broad: any service business that could be
// a viable long-term tenant belongs on the menu. Competition is gated downstream by
// confidence_score, not excluded here.

export type ServiceCategory =
  | 'home_services'
  | 'auto'
  | 'health'
  | 'professional'
  | 'pet'
  | 'event'
  | 'lifestyle'
  | 'legal'
  | 'medical';

/** Canonical category list for zod enums and UI pickers. */
export const CATEGORY_VALUES = [
  'home_services',
  'auto',
  'health',
  'professional',
  'pet',
  'event',
  'lifestyle',
  'legal',
  'medical',
] as const satisfies readonly ServiceCategory[];

export const SERVICE_TAXONOMY: Record<ServiceCategory, string[]> = {
  home_services: [
    // KEEP: high-ticket core (remodeling, structural, HVAC, plumbing, electrical,
    // roofing, restoration) — every entry here has a benchmark above the floor.
    'epoxy garage flooring',
    'gutter guard installation',
    // CUT gutter cleaning (low-ticket seasonal)
    // CUT pressure washing (low-ticket seasonal)
    'soft wash roof cleaning',
    // CUT window cleaning (low-ticket seasonal)
    'solar panel cleaning',
    'christmas light installation',
    'holiday light installation',
    'fence installation',
    'fence repair',
    'vinyl fence installation',
    'wrought iron fence installation',
    'deck building',
    'deck staining',
    'deck repair',
    'pergola installation',
    'patio cover installation',
    'concrete patio installation',
    'stamped concrete',
    'concrete driveway installation',
    'driveway sealing',
    'asphalt paving',
    'paver patio installation',
    'retaining wall installation',
    'landscape design',
    'landscape lighting installation',
    'sod installation',
    'artificial turf installation',
    // CUT lawn aeration (low-ticket seasonal)
    // CUT lawn fertilization (low-ticket seasonal)
    'mosquito control',
    'tick control',
    'sprinkler system installation',
    'sprinkler repair',
    'drip irrigation installation',
    'french drain installation',
    'yard drainage',
    'tree trimming',
    'stump grinding',
    'shrub trimming',
    'mulch installation',
    // CUT leaf removal (low-ticket seasonal)
    // CUT snow removal (low-ticket seasonal)
    'pool installation',
    'pool resurfacing',
    'pool cleaning',
    'hot tub repair',
    'outdoor kitchen installation',
    'fire pit installation',
    'gazebo installation',
    'shed installation',
    'pole barn construction',
    'garage door installation',
    'garage door repair',
    'garage storage installation',
    'garage cabinet installation',
    'overhead storage installation',
    'epoxy basement flooring',
    'basement waterproofing',
    'basement finishing',
    'crawl space encapsulation',
    'foundation repair',
    'sump pump installation',
    'egress window installation',
    'window replacement',
    // CUT window tinting (low-ticket, better in auto)
    'door installation',
    'storm door installation',
    'siding installation',
    'siding repair',
    'soffit and fascia repair',
    'stucco repair',
    'exterior painting',
    'interior painting',
    'cabinet painting',
    'cabinet refinishing',
    'cabinet refacing',
    'kitchen remodeling',
    'bathroom remodeling',
    'shower remodeling',
    'tub to shower conversion',
    'walk in shower installation',
    'countertop installation',
    'quartz countertop installation',
    'tile installation',
    'backsplash installation',
    // CUT grout cleaning (low-ticket)
    'hardwood floor installation',
    'hardwood floor refinishing',
    'laminate flooring installation',
    'vinyl plank flooring installation',
    'carpet installation',
    // CUT carpet cleaning (low-ticket cleaning)
    // CUT upholstery cleaning (low-ticket)
    // CUT tile and grout cleaning (low-ticket)
    'air duct cleaning',
    // CUT dryer vent cleaning (low-ticket seasonal)
    // CUT chimney sweep (low-ticket seasonal)
    'chimney repair',
    'fireplace installation',
    'gas line installation',
    'water heater installation',
    'tankless water heater installation',
    'water softener installation',
    'water filtration installation',
    'drain cleaning',
    'sewer line repair',
    'trenchless sewer repair',
    'leak detection',
    'toilet installation',
    'faucet installation',
    'garbage disposal installation',
    'whole house repipe',
    'well pump repair',
    'septic tank pumping',
    'septic system installation',
    'electrical panel upgrade',
    'ev charger installation',
    'ceiling fan installation',
    'recessed lighting installation',
    'generator installation',
    'whole house generator installation',
    'smart home installation',
    'home theater installation',
    'tv mounting',
    'security camera installation',
    'alarm system installation',
    'low voltage wiring',
    'attic insulation',
    'spray foam insulation',
    'blown in insulation',
    'radiant barrier installation',
    'mini split installation',
    'heat pump installation',
    'thermostat installation',
    'duct sealing',
    'metal roof installation',
    'flat roof repair',
    'skylight installation',
    'termite treatment',
    'bed bug treatment',
    'rodent removal',
    'wildlife removal',
    'bat removal',
    'mold remediation',
    'water damage restoration',
    'fire damage restoration',
    // CUT junk removal (low-ticket)
    'hoarding cleanup',
    'estate cleanout',
    'dumpster rental',
    // CUT house cleaning (low-ticket)
    'move out cleaning',
    'post construction cleaning',
    // CUT handyman services (too generic / low-ticket avg)
    'drywall repair',
    'popcorn ceiling removal',
    'wallpaper installation',
    'closet organization',
    'pool deck resurfacing',
  ],
  auto: [
    // KEEP: higher-ticket mechanical / specialty
    'ceramic coating',
    'paint protection film installation',
    'paintless dent repair',
    'auto body repair',
    'bumper repair',
    'mobile mechanic',
    'brake repair',
    'transmission repair',
    'auto ac repair',
    'car audio installation',
    'remote car starter installation',
    'vehicle wrapping',
    'truck accessories installation',
    'truck bed liner installation',
    'lift kit installation',
    'rv repair',
    'motorcycle repair',
    'diesel repair',
    'mobile rv detailing',
    // CUT: detailing, glass, locksmith, tinting, oil change, tire,
    // alignment, fleet washing, headlight restoration, boat detailing
  ],
  health: [
    // KEEP: high-ticket or meaningful ability-to-pay
    'personal training',
    'in home personal training',
    'mobile personal training',
    'med spa',
    'medical spa',
    'cryotherapy',
    'infrared sauna',
    'float therapy',
    'yoga studio',
    'pilates studio',
    'barre studio',
    'spin studio',
    'crossfit gym',
    'martial arts studio',
    'kids gymnastics',
    'nutrition coaching',
    'wellness coaching',
    // CUT: low-ticket personal-care / retail (massage, nail/hair salon,
    // barbershop, lash, waxing, spray tan, facial, teeth whitening, microblading)
  ],
  professional: [
    // KEEP: recurring/higher-ticket B2B or clear lead-gen fit
    'bookkeeping services',
    'tax preparation',
    'payroll services',
    'small business consulting',
    'managed it services',
    'it support services',
    'web design services',
    'seo services',
    'social media management',
    'commercial photography',
    'real estate photography',
    'drone photography',
    'video production services',
    // KEEP: B2B commercial cleaning (operator confirmed)
    'commercial cleaning',
    'office cleaning',
    'janitorial services',
    'window washing commercial',
    'process server',
    'private investigator',
    'security guard services',
    'staffing agency',
    // CUT: tutoring, lessons, resume, notary, translation, VA, driving school,
    // voice over, computer repair, document shredding
  ],
  pet: [
    // KEEP: higher-ticket or specialized enough to hold rent
    'dog training',
    'in home dog training',
    'puppy training',
    'horse boarding',
    'equine massage',
    'invisible fence installation',
    'dog kennel installation',
    'pet cremation services',
    // CUT: low-ticket grooming (dog/cat/mobile), dog walking, pet sitting,
    // waste removal, daycare, pet taxi, mobile cat grooming, pet photography,
    // aquarium maintenance, mobile pet vaccination
  ],
  event: [
    // KEEP: meaningful contract value, clear lead-gen use case
    'wedding photography',
    'wedding videography',
    'event planning',
    'wedding planning',
    'mobile bartending',
    'catering services',
    'food truck catering',
    'limo service',
    'party bus rental',
    'wedding officiant',
    'led wall rental',
    'event lighting rental',
    'wedding cake bakery',
    // CUT: booths, DJ, bounce/tent/table rentals, balloon, axe/petting-zoo/bull,
    // face painting, event florist, wedding florist (both cut per operator decision)
  ],
  lifestyle: [
    // KEEP: clear contract value, specialised enough to hold rent
    'professional organizer',
    'home organization services',
    'piano moving',
    'local moving services',
    'packing services',
    'art installation services',
    'holiday decorating services',
    'interior decorating',
    'home inspection',
    'reupholstery services',
    'furniture restoration',
    'antique restoration',
    // CUT: car wash, meal prep, personal chef/shopping, laundry/dry-clean delivery,
    // knife sharpening, furniture assembly, sewing, bike repair, house sitting,
    // errand running, senior companion care, mobile detailing, gun cleaning,
    // firewood delivery, pool table moving, pressure cooking classes
  ],
  legal: [
    'personal injury lawyer',
    'car accident lawyer',
    'truck accident lawyer',
    'motorcycle accident lawyer',
    'slip and fall lawyer',
    'workers compensation lawyer',
    'dui lawyer',
    'criminal defense lawyer',
    'traffic ticket lawyer',
    'expungement lawyer',
    'divorce lawyer',
    'family law attorney',
    'child custody lawyer',
    'estate planning attorney',
    'probate lawyer',
    'wills and trusts attorney',
    'bankruptcy lawyer',
    'immigration lawyer',
    'employment lawyer',
    'wrongful termination lawyer',
    'real estate attorney',
    'business attorney',
    'medical malpractice lawyer',
    'nursing home abuse lawyer',
    'social security disability lawyer',
    'landlord tenant attorney',
    'mediation services',
    'mobile notary signing agent',
  ],
  medical: [
    'general dentist',
    'cosmetic dentist',
    'pediatric dentist',
    'emergency dentist',
    'dental implants',
    'orthodontist',
    'invisalign provider',
    'oral surgeon',
    'denture clinic',
    'endodontist',
    'periodontist',
    'chiropractor',
    'sports chiropractor',
    'physical therapy clinic',
    'sports physical therapy',
    'occupational therapy',
    'acupuncture clinic',
    'podiatrist',
    'dermatology clinic',
    'optometrist',
    'lasik eye surgery',
    'audiologist hearing aids',
    'urgent care clinic',
    'primary care clinic',
    'pediatric clinic',
    'weight loss clinic',
    'iv therapy clinic',
    'hormone therapy clinic',
    'mental health counseling',
    'addiction treatment center',
    'veterinary clinic',
    'mobile veterinarian',
  ],
};
