// Seed taxonomy of local service-business trades, grouped by the 9 niche-hunter
// categories. Injected into the brainstorm system prompt to broaden scope beyond
// the saturated home-services tropes the model defaults to. The category keys
// here MUST stay in sync with the CategoryEnum defined in index.ts
// (home_services, auto, health, professional, pet, event, lifestyle, legal, medical).
//
// legal/medical are licensed professions. The platform does NOT verify licenses —
// every site is rented to a real contractor/practice who brings their own license,
// GBP, and regulated-profession ad compliance (bar/board disclaimers, no outcome
// guarantees). Scope here is deliberately broad: any service business that could be
// a viable long-term tenant belongs on the menu. Competition is gated downstream by
// confidence_score, not excluded here.

export type ServiceCategory =
  | 'home_services'
  | 'auto'
  | 'health'
  | 'professional'
  | 'pet'
  | 'event'
  | 'lifestyle'
  | 'legal'
  | 'medical';

export const SERVICE_TAXONOMY: Record<ServiceCategory, string[]> = {
  home_services: [
    'epoxy garage flooring',
    'gutter guard installation',
    'gutter cleaning',
    'pressure washing',
    'soft wash roof cleaning',
    'window cleaning',
    'solar panel cleaning',
    'christmas light installation',
    'holiday light installation',
    'fence installation',
    'fence repair',
    'vinyl fence installation',
    'wrought iron fence installation',
    'deck building',
    'deck staining',
    'deck repair',
    'pergola installation',
    'patio cover installation',
    'concrete patio installation',
    'stamped concrete',
    'concrete driveway installation',
    'driveway sealing',
    'asphalt paving',
    'paver patio installation',
    'retaining wall installation',
    'landscape design',
    'landscape lighting installation',
    'sod installation',
    'artificial turf installation',
    'lawn aeration',
    'lawn fertilization',
    'mosquito control',
    'tick control',
    'sprinkler system installation',
    'sprinkler repair',
    'drip irrigation installation',
    'french drain installation',
    'yard drainage',
    'tree trimming',
    'stump grinding',
    'shrub trimming',
    'mulch installation',
    'leaf removal',
    'snow removal',
    'pool installation',
    'pool resurfacing',
    'pool cleaning',
    'hot tub repair',
    'outdoor kitchen installation',
    'fire pit installation',
    'gazebo installation',
    'shed installation',
    'pole barn construction',
    'garage door installation',
    'garage door repair',
    'garage storage installation',
    'garage cabinet installation',
    'overhead storage installation',
    'epoxy basement flooring',
    'basement waterproofing',
    'basement finishing',
    'crawl space encapsulation',
    'foundation repair',
    'sump pump installation',
    'egress window installation',
    'window replacement',
    'window tinting',
    'door installation',
    'storm door installation',
    'siding installation',
    'siding repair',
    'soffit and fascia repair',
    'stucco repair',
    'exterior painting',
    'interior painting',
    'cabinet painting',
    'cabinet refinishing',
    'cabinet refacing',
    'kitchen remodeling',
    'bathroom remodeling',
    'shower remodeling',
    'tub to shower conversion',
    'walk in shower installation',
    'countertop installation',
    'quartz countertop installation',
    'tile installation',
    'backsplash installation',
    'grout cleaning',
    'hardwood floor installation',
    'hardwood floor refinishing',
    'laminate flooring installation',
    'vinyl plank flooring installation',
    'carpet installation',
    'carpet cleaning',
    'upholstery cleaning',
    'tile and grout cleaning',
    'air duct cleaning',
    'dryer vent cleaning',
    'chimney sweep',
    'chimney repair',
    'fireplace installation',
    'gas line installation',
    'water heater installation',
    'tankless water heater installation',
    'water softener installation',
    'water filtration installation',
    'drain cleaning',
    'sewer line repair',
    'trenchless sewer repair',
    'leak detection',
    'toilet installation',
    'faucet installation',
    'garbage disposal installation',
    'whole house repipe',
    'well pump repair',
    'septic tank pumping',
    'septic system installation',
    'electrical panel upgrade',
    'ev charger installation',
    'ceiling fan installation',
    'recessed lighting installation',
    'generator installation',
    'whole house generator installation',
    'smart home installation',
    'home theater installation',
    'tv mounting',
    'security camera installation',
    'alarm system installation',
    'low voltage wiring',
    'attic insulation',
    'spray foam insulation',
    'blown in insulation',
    'radiant barrier installation',
    'mini split installation',
    'heat pump installation',
    'thermostat installation',
    'duct sealing',
    'metal roof installation',
    'flat roof repair',
    'skylight installation',
    'termite treatment',
    'bed bug treatment',
    'rodent removal',
    'wildlife removal',
    'bat removal',
    'mold remediation',
    'water damage restoration',
    'fire damage restoration',
    'junk removal',
    'hoarding cleanup',
    'estate cleanout',
    'dumpster rental',
    'house cleaning',
    'move out cleaning',
    'post construction cleaning',
    'handyman services',
    'drywall repair',
    'popcorn ceiling removal',
    'wallpaper installation',
    'closet organization',
    'pool deck resurfacing',
  ],
  auto: [
    'mobile car detailing',
    'auto detailing',
    'ceramic coating',
    'paint protection film installation',
    'auto window tinting',
    'auto glass replacement',
    'windshield repair',
    'mobile windshield replacement',
    'paintless dent repair',
    'auto body repair',
    'bumper repair',
    'mobile mechanic',
    'mobile oil change',
    'brake repair',
    'transmission repair',
    'auto ac repair',
    'car audio installation',
    'remote car starter installation',
    'vehicle wrapping',
    'truck accessories installation',
    'truck bed liner installation',
    'lift kit installation',
    'wheel alignment',
    'tire installation',
    'mobile tire repair',
    'rv repair',
    'motorcycle repair',
    'boat detailing',
    'fleet washing',
    'diesel repair',
    'mobile rv detailing',
    'headlight restoration',
    'car key replacement',
    'auto locksmith',
  ],
  health: [
    'personal training',
    'in home personal training',
    'mobile personal training',
    'massage therapy',
    'mobile massage therapy',
    'med spa',
    'medical spa',
    'cryotherapy',
    'infrared sauna',
    'float therapy',
    'yoga studio',
    'pilates studio',
    'barre studio',
    'spin studio',
    'crossfit gym',
    'martial arts studio',
    'kids gymnastics',
    'nutrition coaching',
    'wellness coaching',
    'lash extensions',
    'microblading',
    'spray tanning',
    'mobile spray tanning',
    'teeth whitening',
    'waxing studio',
    'nail salon',
    'mobile manicure and pedicure',
    'hair salon',
    'mobile hair stylist',
    "men's barbershop",
    'mobile barber',
    'facial spa',
  ],
  professional: [
    'bookkeeping services',
    'tax preparation',
    'payroll services',
    'small business consulting',
    'notary services',
    'mobile notary',
    'resume writing services',
    'virtual assistant services',
    'it support services',
    'managed it services',
    'computer repair',
    'mobile computer repair',
    'web design services',
    'seo services',
    'social media management',
    'commercial photography',
    'real estate photography',
    'drone photography',
    'video production services',
    'voice over services',
    'translation services',
    'private tutoring',
    'sat tutoring',
    'music lessons',
    'guitar lessons',
    'driving school',
    'commercial cleaning',
    'office cleaning',
    'janitorial services',
    'window washing commercial',
    'process server',
    'private investigator',
    'security guard services',
    'document shredding',
    'staffing agency',
  ],
  pet: [
    'mobile dog grooming',
    'dog grooming',
    'cat grooming',
    'dog training',
    'in home dog training',
    'puppy training',
    'dog boarding',
    'dog daycare',
    'pet sitting',
    'dog walking',
    'dog waste removal',
    'pooper scooper service',
    'mobile pet vaccination',
    'pet photography',
    'aquarium maintenance',
    'horse boarding',
    'equine massage',
    'invisible fence installation',
    'dog kennel installation',
    'pet taxi service',
    'pet cremation services',
    'mobile cat grooming',
  ],
  event: [
    'wedding photography',
    'wedding videography',
    'photo booth rental',
    'wedding photo booth rental',
    'dj services',
    'wedding dj',
    'event planning',
    'wedding planning',
    'party rental',
    'bounce house rental',
    'tent rental',
    'table and chair rental',
    'inflatable rental',
    'mobile bartending',
    'catering services',
    'food truck catering',
    'balloon decoration',
    'event florist',
    'wedding florist',
    'limo service',
    'party bus rental',
    'mobile axe throwing',
    'mobile petting zoo',
    'face painting',
    'wedding officiant',
    'mobile mechanical bull rental',
    'led wall rental',
    'event lighting rental',
    'wedding cake bakery',
  ],
  lifestyle: [
    'professional organizer',
    'home organization services',
    'personal chef',
    'meal prep services',
    'personal shopping',
    'house sitting',
    'errand running services',
    'senior companion care',
    'mobile car wash',
    'laundry pickup and delivery',
    'dry cleaning delivery',
    'mobile knife sharpening',
    'piano moving',
    'local moving services',
    'packing services',
    'furniture assembly',
    'art installation services',
    'holiday decorating services',
    'interior decorating',
    'home inspection',
    'mobile detailing',
    'reupholstery services',
    'furniture restoration',
    'antique restoration',
    'sewing and alterations',
    'pressure cooking canning classes',
    'mobile bike repair',
    'pool table moving',
    'gun cleaning services',
    'firewood delivery',
  ],
  legal: [
    'personal injury lawyer',
    'car accident lawyer',
    'truck accident lawyer',
    'motorcycle accident lawyer',
    'slip and fall lawyer',
    'workers compensation lawyer',
    'dui lawyer',
    'criminal defense lawyer',
    'traffic ticket lawyer',
    'expungement lawyer',
    'divorce lawyer',
    'family law attorney',
    'child custody lawyer',
    'estate planning attorney',
    'probate lawyer',
    'wills and trusts attorney',
    'bankruptcy lawyer',
    'immigration lawyer',
    'employment lawyer',
    'wrongful termination lawyer',
    'real estate attorney',
    'business attorney',
    'medical malpractice lawyer',
    'nursing home abuse lawyer',
    'social security disability lawyer',
    'landlord tenant attorney',
    'mediation services',
    'mobile notary signing agent',
  ],
  medical: [
    'general dentist',
    'cosmetic dentist',
    'pediatric dentist',
    'emergency dentist',
    'dental implants',
    'orthodontist',
    'invisalign provider',
    'oral surgeon',
    'denture clinic',
    'endodontist',
    'periodontist',
    'chiropractor',
    'sports chiropractor',
    'physical therapy clinic',
    'sports physical therapy',
    'occupational therapy',
    'acupuncture clinic',
    'podiatrist',
    'dermatology clinic',
    'optometrist',
    'lasik eye surgery',
    'audiologist hearing aids',
    'urgent care clinic',
    'primary care clinic',
    'pediatric clinic',
    'weight loss clinic',
    'iv therapy clinic',
    'hormone therapy clinic',
    'mental health counseling',
    'addiction treatment center',
    'veterinary clinic',
    'mobile veterinarian',
  ],
};
