import { renderMarkdown } from '../../lib/markdown';
import { substitutePhone } from '../../lib/phone';

interface Props {
  /** Keyword-rich markdown intro. May contain `{{phone}}` tokens. */
  body?: string;
  /** Tenant tracking phone — replaces `{{phone}}` tokens. */
  phone?: string;
  /** Outer section class — variants pass `"ll-longform <variant>-longform"`. */
  className?: string;
}

/**
 * Keyword-rich long-form intro rendered high on the home page (just under the
 * hero/video). Generated by the content engine from the home keyword cluster.
 * Renders nothing when empty, so existing sites are unaffected until backfilled.
 */
export function LongformSection({ body, phone, className }: Props) {
  if (!body || !body.trim()) return null;
  const html = renderMarkdown(phone ? substitutePhone(body, phone) : body);
  return (
    <section className={className ?? 'll-longform'} aria-label="Overview">
      <div className="ll-longform-body" dangerouslySetInnerHTML={{ __html: html }} />
    </section>
  );
}
