import { sanity } from './sanity';

/**
 * Sanity fetch layer for Custom Sites (`cs*` doc types, ADR 0033). Kept
 * separate from lib/sanity.ts so that file doesn't keep growing with a third
 * business line's projections — R&R (`site`), Corporate (`corporateSite`),
 * and Build & Sell (`buildsellSite`) all live there; Custom Sites lives here.
 *
 * No Postgres coupling (ADR 0033 D4) — `csSite` in Sanity is the entire
 * source of truth, resolved by `siteKey` or by `customDomain` (host).
 */

export interface CustomSiteAddress {
  street?: string | null;
  unit?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
}

export interface CustomSiteNavChildLink {
  label?: string | null;
  href?: string | null;
}

export interface CustomSiteNavLink {
  label?: string | null;
  href?: string | null;
  children?: CustomSiteNavChildLink[] | null;
}

export interface CustomSiteRedirect {
  from?: string | null;
  to?: string | null;
}

export interface CustomSiteSeo {
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImageUrl?: string | null;
  /** Page-level noindex override on top of csSite.robotsDisallow (ADR 0033 Amendment 1 D10). */
  noindex?: boolean | null;
  /** Explicit canonical URL override, e.g. a syndicated legal publication (ADR 0033 Amendment 1 D10). */
  canonicalOverride?: string | null;
}

export interface CustomSiteGeo {
  lat?: number | null;
  lng?: number | null;
}

/**
 * Appends Sanity CDN image-transform params to a raw `asset->url` (the GROQ
 * projections below hand back plain URLs, not the sized/hotspot-aware
 * `@sanity/image-url` builder). Caps the source fetched from Sanity so
 * next/image's own srcset widths can't upscale a modest source asset (e.g. a
 * 1920x1080 photo) all the way to a 3840px request — that was the homepage
 * LCP weight problem. `fit=max` never crops/upscales past the cap.
 */
export function csImageUrl(url: string, opts?: { w?: number; q?: number }): string;
export function csImageUrl(url: string | null | undefined, opts?: { w?: number; q?: number }): string | undefined;
export function csImageUrl(url: string | null | undefined, opts?: { w?: number; q?: number }): string | undefined {
  if (!url) return undefined;
  const w = opts?.w ?? 1600;
  const q = opts?.q ?? 75;
  const sep = url.includes('?') ? '&' : '?';
  return `${url}${sep}auto=format&fit=max&w=${w}&q=${q}`;
}

export interface CustomSite {
  _id: string;
  siteKey: string;
  name: string;
  customDomain?: string | null;
  tagline?: string | null;
  phone?: string | null;
  cellPhone?: string | null;
  email?: string | null;
  address?: CustomSiteAddress | null;
  mapUrl?: string | null;
  mapEmbedUrl?: string | null;
  geo?: CustomSiteGeo | null;
  logoUrl?: string | null;
  footerLogoUrl?: string | null;
  bannerImageUrl?: string | null;
  faviconUrl?: string | null;
  ogImageUrl?: string | null;
  navigation?: CustomSiteNavLink[] | null;
  footerNav?: CustomSiteNavLink[] | null;
  leadRecipients?: string[] | null;
  gtmContainerId?: string | null;
  sameAs?: string[] | null;
  organizationType?: string | null;
  openingHours?: string[] | null;
  robotsDisallow?: boolean | null;
  redirects?: CustomSiteRedirect[] | null;
  seo?: CustomSiteSeo | null;
  /** Metadata title template, e.g. "%s | Michael J. Bayard Construction ADR" (ADR 0033 Amendment 1 D10). */
  titleTemplate?: string | null;
  /** Cities/counties/regions the practice serves, feeds LegalService.areaServed (ADR 0033 Amendment 1 D10). */
  areaServed?: string[] | null;
  /** 32-hex IndexNow verification key, served at /{key}.txt (ADR 0033 Amendment 1 D7). readOnly in Studio — generated by scripts/customsites-indexnow.ts. */
  indexnowKey?: string | null;
  /** Plain-text compliance line shown above the footer legal row on every page. */
  footerDisclosure?: string | null;
}

const CUSTOM_SITE_PROJECTION = `{
  _id, siteKey, name, customDomain, tagline, phone, cellPhone, email,
  address{ street, unit, city, state, zip },
  mapUrl, mapEmbedUrl,
  geo{ lat, lng },
  "logoUrl": logo.asset->url,
  "footerLogoUrl": footerLogo.asset->url,
  "bannerImageUrl": bannerImage.asset->url,
  "faviconUrl": favicon.asset->url,
  "ogImageUrl": ogImage.asset->url,
  navigation[]{ label, href, children[]{ label, href } },
  footerNav[]{ label, href, children[]{ label, href } },
  leadRecipients, gtmContainerId, sameAs, organizationType, openingHours,
  robotsDisallow,
  redirects[]{ from, to },
  seo{ metaTitle, metaDescription, "ogImageUrl": ogImage.asset->url, noindex, canonicalOverride },
  titleTemplate, areaServed, indexnowKey, footerDisclosure
}`;

const CUSTOM_SITE_BY_KEY_QUERY = `*[_type=="csSite" && siteKey==$siteKey][0]${CUSTOM_SITE_PROJECTION}`;
const CUSTOM_SITE_BY_HOST_QUERY = `*[_type=="csSite" && customDomain==$host][0]${CUSTOM_SITE_PROJECTION}`;

export async function fetchCustomSiteByKey(siteKey: string): Promise<CustomSite | null> {
  const result = await sanity.fetch<CustomSite | null>(CUSTOM_SITE_BY_KEY_QUERY, { siteKey });
  return result ?? null;
}

/**
 * Strip port and a leading "www." so both the apex and www resolve to the
 * same bare-apex value stored in csSite.customDomain. Mirrors
 * fetchBuildSellSiteByHost's host normalization in lib/sanity.ts.
 */
export function normalizeCustomHost(host: string): string {
  return host.split(':')[0]!.toLowerCase().replace(/^www\./, '');
}

export async function fetchCustomSiteByHost(host: string): Promise<CustomSite | null> {
  const bare = normalizeCustomHost(host);
  const result = await sanity.fetch<CustomSite | null>(CUSTOM_SITE_BY_HOST_QUERY, { host: bare });
  return result ?? null;
}

// --- Content stubs for sitemap / llms.txt / llms-full.txt / md -------------
// Minimal projections — just enough for the crawl-surface routes in this
// phase. Phase 3's page rendering will likely want richer projections
// (pageBuilder / body) added alongside these, not instead of them.

export interface CustomSitePageStub {
  slug: string;
  title: string;
  modifiedAt?: string | null;
  publishedAt?: string | null;
  /** csPage.seo.metaDescription — used as the llms.txt link description. */
  description?: string | null;
}

export interface CustomSitePracticeAreaStub {
  slug: string;
  title: string;
  excerpt?: string | null;
  modifiedAt?: string | null;
  publishedAt?: string | null;
}

export interface CustomSitePublicationStub {
  slug: string;
  title: string;
  excerpt?: string | null;
  modifiedAt?: string | null;
  publishedAt?: string | null;
}

const CS_PAGE_LIST_QUERY = `*[_type=="csPage" && site->siteKey==$siteKey && defined(slug.current)]{
  "slug": slug.current, title, modifiedAt, publishedAt, "description": seo.metaDescription
}`;

const CS_PRACTICE_AREA_LIST_QUERY = `*[_type=="csPracticeArea" && site->siteKey==$siteKey && defined(slug.current)]{
  "slug": slug.current, title, excerpt, modifiedAt, publishedAt, order
} | order(order asc)`;

const CS_PUBLICATION_LIST_QUERY = `*[_type=="csPublication" && site->siteKey==$siteKey && defined(slug.current)]{
  "slug": slug.current, title, excerpt, modifiedAt, publishedAt
} | order(publishedAt desc)`;

export async function fetchCustomSitePages(siteKey: string): Promise<CustomSitePageStub[]> {
  const result = await sanity.fetch<CustomSitePageStub[] | null>(CS_PAGE_LIST_QUERY, { siteKey });
  return result ?? [];
}

export async function fetchCustomSitePracticeAreas(siteKey: string): Promise<CustomSitePracticeAreaStub[]> {
  const result = await sanity.fetch<CustomSitePracticeAreaStub[] | null>(CS_PRACTICE_AREA_LIST_QUERY, { siteKey });
  return result ?? [];
}

export async function fetchCustomSitePublications(siteKey: string): Promise<CustomSitePublicationStub[]> {
  const result = await sanity.fetch<CustomSitePublicationStub[] | null>(CS_PUBLICATION_LIST_QUERY, { siteKey });
  return result ?? [];
}

// --- Phase 3: full projections for page rendering ---------------------------
// Additive to the stubs above (kept for sitemap/llms.txt/md), not a
// replacement — those routes only need slug/title/excerpt/dates.

export interface CsPortableTextBlock {
  _type: string;
  _key: string;
  /** Present on image members (asset deref'd to url/dims below). */
  url?: string;
  dims?: { width?: number; height?: number } | null;
  alt?: string | null;
  caption?: string | null;
  [key: string]: unknown;
}

/** Portable Text array member projection — spreads all block fields, and
 * deref's `asset` on image members to a plain url + dimensions. */
const CS_BODY_MEMBER_PROJECTION = `{
  ...,
  _type == "image" => {
    "url": asset->url,
    "dims": asset->metadata.dimensions
  }
}`;

const CS_BODY_PROJECTION = `[]${CS_BODY_MEMBER_PROJECTION}`;

export interface CsFaqItem {
  question: string;
  answer: string;
}

/** csCredential — a non-bar-admission credential (AAA/ICC certification, judicial-reference
 * appointment, etc.). Feeds hasCredential JSON-LD generically (ADR 0033 Amendment 1 D10). */
export interface CustomSiteCredential {
  name: string;
  issuer?: string | null;
  year?: number | null;
  url?: string | null;
}

/** csBarAdmission — structured bar admission. Maps to hasCredential's
 * credentialCategory: 'license' + recognizedBy shape (ADR 0033 Amendment 1 D10). */
export interface CustomSiteBarAdmission {
  jurisdiction: string;
  barNumber?: string | null;
  admittedYear?: number | null;
}

export interface CustomSiteAttorney {
  _id: string;
  name: string;
  slug: string;
  jobTitle?: string | null;
  photoUrl?: string | null;
  photoAlt?: string | null;
  bio?: CsPortableTextBlock[] | null;
  bioSections?: Array<{ heading?: string | null; content?: CsPortableTextBlock[] | null }> | null;
  credentials?: CustomSiteCredential[] | null;
  barAdmissions?: CustomSiteBarAdmission[] | null;
  arbitratorPanels?: string[] | null;
  sameAs?: string[] | null;
  email?: string | null;
  phone?: string | null;
  vCardUrl?: string | null;
}

const CS_ATTORNEY_PROJECTION = `{
  _id, name, "slug": slug.current, jobTitle,
  "photoUrl": photo.asset->url,
  "photoAlt": photo.alt,
  bio${CS_BODY_PROJECTION},
  bioSections[]{ heading, content${CS_BODY_PROJECTION} },
  credentials[]{ name, issuer, year, url },
  barAdmissions[]{ jurisdiction, barNumber, admittedYear },
  arbitratorPanels,
  sameAs, email, phone,
  "vCardUrl": vCard.asset->url
}`;

export interface CustomSitePracticeAreaCard {
  _id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  order?: number | null;
  cardImageUrl?: string | null;
  cardImageAlt?: string | null;
  /** Nav/rail label when the full title is too long. */
  shortLabel?: string | null;
  /** Individual services in this focus area — csFocusAreaListBlock renders the
   * list and shows `deliverables.length` as the count. */
  deliverables?: string[] | null;
}

// `order` is projected because the sort runs after the projection: without it
// `| order(order asc)` has no field to sort on and falls back to id order.
const CS_PRACTICE_AREA_CARD_PROJECTION = `{
  _id, title, "slug": slug.current, excerpt, order,
  "cardImageUrl": cardImage.asset->url,
  "cardImageAlt": cardImage.alt,
  shortLabel, deliverables
}`;

export interface CustomSitePracticeAreaFull {
  _id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImageUrl?: string | null;
  heroImageAlt?: string | null;
  cardImageUrl?: string | null;
  body?: CsPortableTextBlock[] | null;
  faqs?: CsFaqItem[] | null;
  order?: number | null;
  shortLabel?: string | null;
  deliverables?: string[] | null;
  publishedAt?: string | null;
  modifiedAt?: string | null;
  seo?: CustomSiteSeo | null;
}

const CS_PRACTICE_AREA_FULL_PROJECTION = `{
  _id, title, "slug": slug.current, excerpt,
  "heroImageUrl": heroImage.asset->url,
  "heroImageAlt": heroImage.alt,
  "cardImageUrl": cardImage.asset->url,
  body${CS_BODY_PROJECTION},
  faqs[]{ question, answer },
  order, shortLabel, deliverables, publishedAt, modifiedAt,
  seo{ metaTitle, metaDescription, "ogImageUrl": ogImage.asset->url, noindex, canonicalOverride }
}`;

export interface CsListenLink {
  platform: 'spotify' | 'apple' | 'youtube' | 'other';
  url: string;
  label?: string | null;
}

export interface CustomSitePublicationFull {
  _id: string;
  title: string;
  slug: string;
  kind: 'article' | 'publication' | 'presentation';
  excerpt?: string | null;
  body?: CsPortableTextBlock[] | null;
  publishedAt: string;
  modifiedAt?: string | null;
  /** Podcast episode number — absent for anything that isn't an episode. */
  episodeNumber?: number | null;
  /** Runtime in whole minutes, rendered as "42 min". */
  durationMinutes?: number | null;
  listenLinks?: CsListenLink[] | null;
  externalEvent?: string | null;
  externalDate?: string | null;
  coAuthors?: string | null;
  pdfUrl?: string | null;
  featuredImageUrl?: string | null;
  featuredImageAlt?: string | null;
  authorName?: string | null;
  authorSlug?: string | null;
  seo?: CustomSiteSeo | null;
}

const CS_PUBLICATION_FULL_PROJECTION = `{
  _id, title, "slug": slug.current, kind, excerpt,
  body${CS_BODY_PROJECTION},
  publishedAt, modifiedAt, episodeNumber, durationMinutes,
  listenLinks[]{ platform, url, label },
  externalEvent, externalDate, coAuthors,
  "pdfUrl": pdf.asset->url,
  "featuredImageUrl": featuredImage.asset->url,
  "featuredImageAlt": featuredImage.alt,
  "authorName": author->name,
  "authorSlug": author->slug.current,
  seo{ metaTitle, metaDescription, "ogImageUrl": ogImage.asset->url, noindex, canonicalOverride }
}`;

// --- Site #2 document types (journey stages, case studies, assessments) -----

export interface CustomSiteJourneyStage {
  _id: string;
  order: number;
  title: string;
  slug: string;
  shortLabel?: string | null;
  summary: string;
  nextStageTeaser?: string | null;
  focusAreas?: CustomSitePracticeAreaCard[] | null;
  body?: CsPortableTextBlock[] | null;
}

const CS_JOURNEY_STAGE_PROJECTION = `{
  _id, order, title, "slug": slug.current, shortLabel, summary, nextStageTeaser,
  "focusAreas": focusAreas[]->${CS_PRACTICE_AREA_CARD_PROJECTION},
  body${CS_BODY_PROJECTION}
}`;

export async function fetchCustomSiteJourneyStages(siteKey: string): Promise<CustomSiteJourneyStage[]> {
  const query = `*[_type=="csJourneyStage" && site->siteKey==$siteKey]${CS_JOURNEY_STAGE_PROJECTION} | order(order asc)`;
  const result = await sanity.fetch<CustomSiteJourneyStage[] | null>(query, { siteKey });
  return result ?? [];
}

export interface CustomSiteCaseStudy {
  _id: string;
  headline: string;
  slug: string;
  clientDescriptor?: string | null;
  metricLabel: string;
  beforeValue: string;
  afterValue?: string | null;
  timeframe?: string | null;
  narrative?: CsPortableTextBlock[] | null;
  order?: number | null;
  stageTitle?: string | null;
}

const CS_CASE_STUDY_PROJECTION = `{
  _id, headline, "slug": slug.current, clientDescriptor, metricLabel,
  beforeValue, afterValue, timeframe,
  narrative${CS_BODY_PROJECTION},
  order,
  "stageTitle": stage->title
}`;

/** Approved case studies only — the approvedForUse compliance gate is
 * enforced in the query itself, so an unapproved doc can never render no
 * matter which block or route asks for it. */
export async function fetchCustomSiteCaseStudies(siteKey: string): Promise<CustomSiteCaseStudy[]> {
  const query = `*[_type=="csCaseStudy" && site->siteKey==$siteKey && approvedForUse==true]${CS_CASE_STUDY_PROJECTION} | order(order asc)`;
  const result = await sanity.fetch<CustomSiteCaseStudy[] | null>(query, { siteKey });
  return result ?? [];
}

export interface CustomSiteAssessmentOption {
  label: string;
  points: number;
}

export interface CustomSiteAssessmentQuestion {
  prompt: string;
  helpText?: string | null;
  options: CustomSiteAssessmentOption[];
}

export interface CustomSiteAssessmentBand {
  minScore: number;
  maxScore: number;
  resultHeading?: string | null;
  stage?: Pick<CustomSiteJourneyStage, '_id' | 'order' | 'title' | 'slug' | 'summary' | 'nextStageTeaser'> | null;
}

export interface CustomSiteAssessment {
  _id: string;
  title: string;
  slug: string;
  questions: CustomSiteAssessmentQuestion[];
  bands: CustomSiteAssessmentBand[];
  emailSubject?: string | null;
  emailIntro?: string | null;
}

const CS_ASSESSMENT_PROJECTION = `{
  _id, title, "slug": slug.current,
  questions[]{ prompt, helpText, options[]{ label, points } },
  bands[]{
    minScore, maxScore, resultHeading,
    stage->{ _id, order, title, "slug": slug.current, summary, nextStageTeaser }
  },
  emailSubject, emailIntro
}`;

export async function fetchCustomSiteAssessment(siteKey: string, slug: string): Promise<CustomSiteAssessment | null> {
  const query = `*[_type=="csAssessment" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_ASSESSMENT_PROJECTION}`;
  const result = await sanity.fetch<CustomSiteAssessment | null>(query, { siteKey, slug });
  return result ?? null;
}

/** One member of csPage.pageBuilder, conditionally projected by `_type` so the
 * shared field names across block types (e.g. `heading`, `body`) never bleed
 * into the wrong block shape. */
const CS_PAGE_BUILDER_PROJECTION = `pageBuilder[]{
  _type,
  _key,
  _type == "csHeroBlock" => {
    eyebrow, heading, headingEmphasis, subheading, ctaLabel, ctaHref,
    "backgroundImageUrl": backgroundImage.asset->url,
    "backgroundImageAlt": backgroundImage.alt,
    "backgroundVideoUrl": backgroundVideo.asset->url,
    "backgroundVideoMimeType": backgroundVideo.asset->mimeType
  },
  _type == "csIntroBlock" => {
    eyebrow, heading,
    body${CS_BODY_PROJECTION},
    ctaLabel, ctaHref, layout, bodyDividers, topRule
  },
  _type == "csPracticeGridBlock" => {
    eyebrow, heading, mode,
    "areas": areas[]->${CS_PRACTICE_AREA_CARD_PROJECTION}
  },
  _type == "csAttorneyBlock" => {
    showFullProfile,
    "attorney": attorney->${CS_ATTORNEY_PROJECTION}
  },
  _type == "csTestimonialsBlock" => {
    "items": items[]->{ _id, quote, author, role, rating },
    autoRotate
  },
  _type == "csBadgeRowBlock" => {
    eyebrow, heading,
    "badges": badges[]->{ _id, name, "imageUrl": image.asset->url, "imageAlt": image.alt, url }
  },
  _type == "csPublicationsBlock" => {
    eyebrow, heading, limit, ctaLabel, ctaHref
  },
  _type == "csCalloutBlock" => {
    label, quote, linkLabel, linkHref
  },
  _type == "csRichTextBlock" => {
    content${CS_BODY_PROJECTION}
  },
  _type == "csContactCtaBlock" => {
    eyebrow, heading, body, showForm, formVariant, formFootnote,
    checklist[]{ _key, heading, body }
  },
  _type == "csCtaBannerBlock" => {
    heading, ctaLabel, ctaHref
  },
  _type == "csFaqBlock" => {
    heading,
    items[]{ question, answer }
  },
  _type == "csStatRailBlock" => {
    eyebrow, inverse,
    items[]{ _key, value, label, footnote }
  },
  _type == "csValuePropsBlock" => {
    eyebrow, heading,
    items[]{ _key, icon, heading, body }
  },
  _type == "csJourneyBlock" => {
    eyebrow, heading, intro, ctaLabel, ctaHref,
    "stages": stages[]->${CS_JOURNEY_STAGE_PROJECTION}
  },
  _type == "csCompareBlock" => {
    eyebrow, heading, intro, leftLabel, rightLabel,
    rows[]{ _key, leftWho, leftQuote, rightQuote }
  },
  _type == "csTeamGridBlock" => {
    eyebrow, heading, intro, mode, linkToProfiles,
    "members": members[]->{
      _id, name, "slug": slug.current, jobTitle,
      "photoUrl": photo.asset->url, "photoAlt": photo.alt,
      credentials[]{ name, issuer, year, url }
    }
  },
  _type == "csFocusAreaListBlock" => {
    eyebrow, heading, summaryLine, showDeliverableCounts,
    "areas": areas[]->${CS_PRACTICE_AREA_CARD_PROJECTION}
  },
  _type == "csCaseStudyGridBlock" => {
    eyebrow, heading, mode, limit, disclaimer,
    "items": items[]->${CS_CASE_STUDY_PROJECTION}
  },
  _type == "csNumbersIqBlock" => {
    eyebrow, heading,
    body${CS_BODY_PROJECTION},
    metrics[]{ _key, label, percent, valueLabel },
    ctaLabel, ctaHref, illustrative
  },
  _type == "csLeadMagnetBlock" => {
    eyebrow, heading,
    items[]{
      _key, title, body, gated, ctaLabel,
      "pdfUrl": pdf.asset->url,
      "pdfAssetId": pdf.asset->_id
    }
  },
  _type == "csTabbedInsightsBlock" => {
    eyebrow,
    tabs[]{ _key, label, sublabel, href, icon }
  },
  _type == "csEpisodeListBlock" => {
    eyebrow, heading, kind, limit, showListenLinks, ctaLabel, ctaHref
  },
  _type == "csAssessmentBlock" => {
    introHeading, introBody, startLabel, captureTiming, resultCtaLabel, resultCtaHref,
    "quiz": quiz->${CS_ASSESSMENT_PROJECTION}
  },
  _type == "csDisclosureBlock" => {
    heading, lastUpdated,
    content${CS_BODY_PROJECTION},
    note
  }
}`;

export interface CsHeroBlock { _type: 'csHeroBlock'; _key: string; eyebrow?: string | null; heading: string; headingEmphasis?: string | null; subheading?: string | null; ctaLabel?: string | null; ctaHref?: string | null; backgroundImageUrl?: string | null; backgroundImageAlt?: string | null; backgroundVideoUrl?: string | null; backgroundVideoMimeType?: string | null }
export interface CsIntroBlock { _type: 'csIntroBlock'; _key: string; eyebrow?: string | null; heading?: string | null; body?: CsPortableTextBlock[] | null; ctaLabel?: string | null; ctaHref?: string | null; layout?: 'split' | 'stacked' | null; bodyDividers?: boolean | null; topRule?: boolean | null }
export interface CsPracticeGridBlock { _type: 'csPracticeGridBlock'; _key: string; eyebrow?: string | null; heading?: string | null; mode?: 'all' | 'selected' | null; areas?: CustomSitePracticeAreaCard[] | null }
export interface CsAttorneyBlock { _type: 'csAttorneyBlock'; _key: string; showFullProfile?: boolean | null; attorney?: CustomSiteAttorney | null }
export interface CsTestimonialItem {
  _id: string;
  quote: string;
  author?: string | null;
  role?: string | null;
  /** 1-5, only for a real attributable rating — never fabricated (ADR 0033 Amendment 1 D10). */
  rating?: number | null;
}
export interface CsTestimonialsBlock { _type: 'csTestimonialsBlock'; _key: string; items?: CsTestimonialItem[] | null; autoRotate?: boolean | null }
export interface CsBadgeItem { _id: string; name: string; imageUrl?: string | null; imageAlt?: string | null; url?: string | null }
export interface CsBadgeRowBlock { _type: 'csBadgeRowBlock'; _key: string; eyebrow?: string | null; heading?: string | null; badges?: CsBadgeItem[] | null }
export interface CsPublicationsBlock { _type: 'csPublicationsBlock'; _key: string; eyebrow?: string | null; heading?: string | null; limit?: number | null; ctaLabel?: string | null; ctaHref?: string | null }
export interface CsCalloutBlock { _type: 'csCalloutBlock'; _key: string; label?: string | null; quote?: string | null; linkLabel?: string | null; linkHref?: string | null }
export interface CsRichTextBlock { _type: 'csRichTextBlock'; _key: string; content?: CsPortableTextBlock[] | null }
export interface CsContactChecklistItem { _key: string; heading: string; body?: string | null }
export interface CsContactCtaBlock { _type: 'csContactCtaBlock'; _key: string; eyebrow?: string | null; heading?: string | null; body?: string | null; showForm?: boolean | null; formVariant?: 'standard' | 'consultation' | null; formFootnote?: string | null; checklist?: CsContactChecklistItem[] | null }
export interface CsCtaBannerBlock { _type: 'csCtaBannerBlock'; _key: string; heading?: string | null; ctaLabel?: string | null; ctaHref?: string | null }
export interface CsFaqBlock { _type: 'csFaqBlock'; _key: string; heading?: string | null; items?: CsFaqItem[] | null }

export interface CsStatRailItem { _key: string; value: string; label: string; footnote?: string | null }
export interface CsStatRailBlock { _type: 'csStatRailBlock'; _key: string; eyebrow?: string | null; inverse?: boolean | null; items?: CsStatRailItem[] | null }

export type CsValuePropIcon = 'team' | 'practice' | 'roadmap' | 'shield' | 'chart' | 'clock';
export interface CsValuePropItem { _key: string; icon?: CsValuePropIcon | null; heading: string; body: string }
export interface CsValuePropsBlock { _type: 'csValuePropsBlock'; _key: string; eyebrow?: string | null; heading?: string | null; items?: CsValuePropItem[] | null }

export interface CsJourneyBlock { _type: 'csJourneyBlock'; _key: string; eyebrow?: string | null; heading?: string | null; intro?: string | null; ctaLabel?: string | null; ctaHref?: string | null; stages?: CustomSiteJourneyStage[] | null }

export interface CsCompareRow { _key: string; leftWho: string; leftQuote: string; rightQuote: string }
export interface CsCompareBlock { _type: 'csCompareBlock'; _key: string; eyebrow?: string | null; heading?: string | null; intro?: string | null; leftLabel?: string | null; rightLabel?: string | null; rows?: CsCompareRow[] | null }

export interface CsTeamMemberCard { _id: string; name: string; slug: string; jobTitle?: string | null; photoUrl?: string | null; photoAlt?: string | null; credentials?: CustomSiteCredential[] | null }
export interface CsTeamGridBlock { _type: 'csTeamGridBlock'; _key: string; eyebrow?: string | null; heading?: string | null; intro?: string | null; mode?: 'all' | 'selected' | null; linkToProfiles?: boolean | null; members?: CsTeamMemberCard[] | null }

export interface CsFocusAreaListBlock { _type: 'csFocusAreaListBlock'; _key: string; eyebrow?: string | null; heading?: string | null; summaryLine?: string | null; showDeliverableCounts?: boolean | null; areas?: CustomSitePracticeAreaCard[] | null }

export interface CsCaseStudyGridBlock { _type: 'csCaseStudyGridBlock'; _key: string; eyebrow?: string | null; heading?: string | null; mode?: 'all' | 'selected' | null; limit?: number | null; disclaimer?: string | null; items?: CustomSiteCaseStudy[] | null }

export interface CsNumbersIqMetric { _key: string; label: string; percent: number; valueLabel?: string | null }
export interface CsNumbersIqBlock { _type: 'csNumbersIqBlock'; _key: string; eyebrow?: string | null; heading?: string | null; body?: CsPortableTextBlock[] | null; metrics?: CsNumbersIqMetric[] | null; ctaLabel?: string | null; ctaHref?: string | null; illustrative?: boolean | null }

export interface CsLeadMagnetItem { _key: string; title: string; body: string; gated?: boolean | null; ctaLabel?: string | null; pdfUrl?: string | null; pdfAssetId?: string | null }
export interface CsLeadMagnetBlock { _type: 'csLeadMagnetBlock'; _key: string; eyebrow?: string | null; heading?: string | null; items?: CsLeadMagnetItem[] | null }

export interface CsInsightsTab { _key: string; label: string; sublabel?: string | null; href: string; icon?: 'podcast' | 'mic' | 'doc' | null }
export interface CsTabbedInsightsBlock { _type: 'csTabbedInsightsBlock'; _key: string; eyebrow?: string | null; tabs?: CsInsightsTab[] | null }

export interface CsEpisodeListBlock { _type: 'csEpisodeListBlock'; _key: string; eyebrow?: string | null; heading?: string | null; kind?: 'article' | 'publication' | 'presentation' | null; limit?: number | null; showListenLinks?: boolean | null; ctaLabel?: string | null; ctaHref?: string | null }

export interface CsAssessmentBlock { _type: 'csAssessmentBlock'; _key: string; introHeading?: string | null; introBody?: string | null; startLabel?: string | null; captureTiming?: 'before-result' | 'after-result' | 'never' | null; resultCtaLabel?: string | null; resultCtaHref?: string | null; quiz?: CustomSiteAssessment | null }

export interface CsDisclosureBlock { _type: 'csDisclosureBlock'; _key: string; heading?: string | null; lastUpdated?: string | null; content?: CsPortableTextBlock[] | null; note?: string | null }

export type CsPageBuilderBlock =
  | CsHeroBlock
  | CsIntroBlock
  | CsPracticeGridBlock
  | CsAttorneyBlock
  | CsTestimonialsBlock
  | CsBadgeRowBlock
  | CsPublicationsBlock
  | CsCalloutBlock
  | CsRichTextBlock
  | CsContactCtaBlock
  | CsCtaBannerBlock
  | CsFaqBlock
  | CsStatRailBlock
  | CsValuePropsBlock
  | CsJourneyBlock
  | CsCompareBlock
  | CsTeamGridBlock
  | CsFocusAreaListBlock
  | CsCaseStudyGridBlock
  | CsNumbersIqBlock
  | CsLeadMagnetBlock
  | CsTabbedInsightsBlock
  | CsEpisodeListBlock
  | CsAssessmentBlock
  | CsDisclosureBlock;

export interface CustomSitePageFull {
  _id: string;
  title: string;
  slug: string;
  bannerImageUrl?: string | null;
  bannerImageAlt?: string | null;
  pageBuilder?: CsPageBuilderBlock[] | null;
  seo?: CustomSiteSeo | null;
  publishedAt?: string | null;
  modifiedAt?: string | null;
}

const CS_PAGE_FULL_PROJECTION = `{
  _id, title, "slug": slug.current,
  "bannerImageUrl": bannerImage.asset->url,
  "bannerImageAlt": bannerImage.alt,
  ${CS_PAGE_BUILDER_PROJECTION},
  seo{ metaTitle, metaDescription, "ogImageUrl": ogImage.asset->url, noindex, canonicalOverride },
  publishedAt, modifiedAt
}`;

export async function fetchCustomSitePageBySlug(siteKey: string, slug: string): Promise<CustomSitePageFull | null> {
  const query = `*[_type=="csPage" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_PAGE_FULL_PROJECTION}`;
  const result = await sanity.fetch<CustomSitePageFull | null>(query, { siteKey, slug });
  return result ?? null;
}

export async function fetchCustomSitePracticeAreaCards(siteKey: string): Promise<CustomSitePracticeAreaCard[]> {
  const query = `*[_type=="csPracticeArea" && site->siteKey==$siteKey && defined(slug.current)]${CS_PRACTICE_AREA_CARD_PROJECTION} | order(order asc)`;
  const result = await sanity.fetch<CustomSitePracticeAreaCard[] | null>(query, { siteKey });
  return result ?? [];
}

/** Standalone testimonial list, for pages that show quotes outside a pageBuilder, and for
 * the layout-level Review JSON-LD (CustomSiteJsonLd). */
export async function fetchCustomSiteTestimonials(siteKey: string): Promise<CsTestimonialItem[]> {
  const query = `*[_type=="csTestimonial" && site->siteKey==$siteKey]{_id, quote, author, role, rating} | order(order asc)`;
  const result = await sanity.fetch<CsTestimonialItem[] | null>(query, { siteKey });
  return result ?? [];
}

export async function fetchCustomSitePracticeAreaFull(
  siteKey: string,
  slug: string,
): Promise<CustomSitePracticeAreaFull | null> {
  const query = `*[_type=="csPracticeArea" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_PRACTICE_AREA_FULL_PROJECTION}`;
  const result = await sanity.fetch<CustomSitePracticeAreaFull | null>(query, { siteKey, slug });
  return result ?? null;
}

export async function fetchCustomSitePublicationsFull(siteKey: string): Promise<CustomSitePublicationFull[]> {
  const query = `*[_type=="csPublication" && site->siteKey==$siteKey && defined(slug.current)]${CS_PUBLICATION_FULL_PROJECTION} | order(publishedAt desc)`;
  const result = await sanity.fetch<CustomSitePublicationFull[] | null>(query, { siteKey });
  return result ?? [];
}

export interface CustomSiteAttorneySummary {
  _id: string;
  name: string;
  slug: string;
  jobTitle?: string | null;
  sameAs?: string[] | null;
  credentials?: CustomSiteCredential[] | null;
  barAdmissions?: CustomSiteBarAdmission[] | null;
  arbitratorPanels?: string[] | null;
}

const CS_ATTORNEY_LIST_QUERY = `*[_type=="csAttorney" && site->siteKey==$siteKey] | order(_createdAt asc){
  _id, name, "slug": slug.current, jobTitle, sameAs,
  credentials[]{ name, issuer, year, url },
  barAdmissions[]{ jurisdiction, barNumber, admittedYear },
  arbitratorPanels
}`;

/** Attorney summaries for a site, oldest-first (stable "primary attorney"
 * ordering for the layout's Person JSON-LD node when a site has exactly one).
 * Carries enough of csAttorney (credentials/barAdmissions/arbitratorPanels) for
 * the layout-level hasCredential/memberOf JSON-LD without paying for the full
 * bio/bioSections Portable Text payload. */
export async function fetchCustomSiteAttorneys(siteKey: string): Promise<CustomSiteAttorneySummary[]> {
  const result = await sanity.fetch<CustomSiteAttorneySummary[] | null>(CS_ATTORNEY_LIST_QUERY, { siteKey });
  return result ?? [];
}

const CS_TEAM_CARD_QUERY = `*[_type=="csAttorney" && site->siteKey==$siteKey] | order(_createdAt asc){
  _id, name, "slug": slug.current, jobTitle,
  "photoUrl": photo.asset->url, "photoAlt": photo.alt,
  credentials[]{ name, issuer, year, url }
}`;

/** Team roster cards (csTeamGridBlock "all" mode) — name/role/photo only,
 * no bio Portable Text payload. */
export async function fetchCustomSiteTeamCards(siteKey: string): Promise<CsTeamMemberCard[]> {
  const result = await sanity.fetch<CsTeamMemberCard[] | null>(CS_TEAM_CARD_QUERY, { siteKey });
  return result ?? [];
}

/** One attorney/team member's full profile by slug — powers /team/<slug>. */
export async function fetchCustomSiteAttorneyFull(siteKey: string, slug: string): Promise<CustomSiteAttorney | null> {
  const query = `*[_type=="csAttorney" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_ATTORNEY_PROJECTION}`;
  const result = await sanity.fetch<CustomSiteAttorney | null>(query, { siteKey, slug });
  return result ?? null;
}

export interface CustomSiteOgAttorney {
  name: string;
  jobTitle?: string | null;
  photoUrl?: string | null;
  photoAlt?: string | null;
}

const CS_OG_ATTORNEY_QUERY = `*[_type=="csAttorney" && site->siteKey==$siteKey] | order(_createdAt asc)[0]{
  name, jobTitle, "photoUrl": photo.asset->url, "photoAlt": photo.alt
}`;

/**
 * Primary attorney (oldest-first, same ordering as fetchCustomSiteAttorneys /
 * attorneyJsonLdId's `#attorney` convention) with just enough fields for the
 * generated OG image fallback (app/cadr/og/route.tsx) — name/jobTitle/photo,
 * nothing else. Kept separate from CS_ATTORNEY_LIST_QUERY so the layout's
 * JSON-LD fetch doesn't pay for the photo field it never uses.
 */
export async function fetchCustomSiteOgAttorney(siteKey: string): Promise<CustomSiteOgAttorney | null> {
  const result = await sanity.fetch<CustomSiteOgAttorney | null>(CS_OG_ATTORNEY_QUERY, { siteKey });
  return result ?? null;
}

export async function fetchCustomSitePublicationFull(
  siteKey: string,
  slug: string,
): Promise<CustomSitePublicationFull | null> {
  const query = `*[_type=="csPublication" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_PUBLICATION_FULL_PROJECTION}`;
  const result = await sanity.fetch<CustomSitePublicationFull | null>(query, { siteKey, slug });
  return result ?? null;
}

export interface CustomSiteLeadMagnetAsset {
  title: string;
  gated?: boolean | null;
  url: string;
}

/**
 * Resolve a lead-magnet PDF by its Sanity asset id, verified to belong to a
 * csLeadMagnetBlock item on one of THIS site's pages — the magnet kind of
 * /api/cs-lead never trusts a client-supplied URL, only an asset id it can
 * re-derive server-side.
 */
export async function fetchCustomSiteLeadMagnetAsset(
  siteKey: string,
  assetId: string,
): Promise<CustomSiteLeadMagnetAsset | null> {
  const query = `*[_type=="csPage" && site->siteKey==$siteKey]
    .pageBuilder[_type=="csLeadMagnetBlock"]
    .items[pdf.asset._ref==$assetId][0]{ title, gated, "url": pdf.asset->url }`;
  const result = await sanity.fetch<CustomSiteLeadMagnetAsset | null>(query, { siteKey, assetId });
  return result?.url ? result : null;
}

export interface CustomSiteRouteBundle {
  page: CustomSitePageFull | null;
  pub: CustomSitePublicationFull | null;
  redirectTo: string | null;
}

/**
 * Single GROQ round trip for app/cadr/[slug]/page.tsx: resolves whichever of
 * csPage / csPublication / csSite.redirects[].from matches the slug. Callers
 * check `page`, then `pub`, then `redirectTo`, in that order (mirrors the
 * route's disambiguation logic).
 */
export async function fetchCustomSiteRouteBundle(siteKey: string, slug: string): Promise<CustomSiteRouteBundle> {
  const query = `{
    "page": *[_type=="csPage" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_PAGE_FULL_PROJECTION},
    "pub": *[_type=="csPublication" && site->siteKey==$siteKey && slug.current==$slug][0]${CS_PUBLICATION_FULL_PROJECTION},
    "redirectTo": *[_type=="csSite" && siteKey==$siteKey][0].redirects[from==$slug][0].to
  }`;
  const result = await sanity.fetch<CustomSiteRouteBundle>(query, { siteKey, slug });
  return result ?? { page: null, pub: null, redirectTo: null };
}
